[2024-06-06 18:54:48] [INFO] - Logging is configured.
[2024-06-06 18:54:48] [INFO] - init_app | Successfully connected to the MongoDB database.
[2024-06-06 18:54:48] [INFO] - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-06-06 18:54:48] [INFO] - [33mPress CTRL+C to quit[0m
[2024-06-06 18:54:51] [INFO] - 127.0.0.1 - - [06/Jun/2024 18:54:51] "POST /api/v1/contracts/process/retry HTTP/1.1" 200 -
[2024-06-06 18:54:52] [INFO] - runTryAgain | started to process contract: {'_id': ObjectId('665a71c4c301047d98635157'), 'tryAgain': True, 'requestId': 1387, 'createdAt': datetime.datetime(2024, 6, 1, 0, 56, 36, 645000), 'validNewClient': True, 'status': {'name': 'Error', 'descritpion': "Retry Process error cannot access local variable 'serviceType' where it is not associated with a value"}, 'updatedAt': datetime.datetime(2024, 6, 6, 21, 54, 9, 222000)}
[2024-06-06 18:54:53] [ERROR] - runTryAgain | Error processing contract: cannot access local variable 'serviceType' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/aristeu/www/integrations-core/application/blueprints/services/contracts.py", line 222, in runTryAgain
    serviceType, documents = self.processContract(requestId, contractValues)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aristeu/www/integrations-core/application/blueprints/services/contracts.py", line 30, in processContract
    workTypeFormatted = formatting.formatServiceType(workType)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aristeu/www/integrations-core/application/blueprints/utils/formatting.py", line 51, in formatServiceType
    return serviceType
           ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'serviceType' where it is not associated with a value
